//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOEClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<censored>")]
        public string WoodTag {
            get {
                return ((string)(this["WoodTag"]));
            }
            set {
                this["WoodTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("medium rare please")]
        public string FoodTag {
            get {
                return ((string)(this["FoodTag"]));
            }
            set {
                this["FoodTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("give me liberty or give me coin")]
        public string GoldTag {
            get {
                return ((string)(this["GoldTag"]));
            }
            set {
                this["GoldTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nova & orion")]
        public string XPTag {
            get {
                return ((string)(this["XPTag"]));
            }
            set {
                this["XPTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("shiver me timpers!")]
        public string DestroyBoatsTag {
            get {
                return ((string)(this["DestroyBoatsTag"]));
            }
            set {
                this["DestroyBoatsTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("x marks the spot")]
        public string RevealMapTag {
            get {
                return ((string)(this["RevealMapTag"]));
            }
            set {
                this["RevealMapTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("this is too hard")]
        public string WinGameTag {
            get {
                return ((string)(this["WinGameTag"]));
            }
            set {
                this["WinGameTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sooo good")]
        public string MusketeeredTag {
            get {
                return ((string)(this["MusketeeredTag"]));
            }
            set {
                this["MusketeeredTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("George Crushington")]
        public string GeorgeCrushingtonToolTip {
            get {
                return ((string)(this["GeorgeCrushingtonToolTip"]));
            }
            set {
                this["GeorgeCrushingtonToolTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("where\'s that axe?")]
        public string GeorgeCrushington {
            get {
                return ((string)(this["GeorgeCrushington"]));
            }
            set {
                this["GeorgeCrushington"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ya gotta make do with what ya got")]
        public string BigGun {
            get {
                return ((string)(this["BigGun"]));
            }
            set {
                this["BigGun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Spawns Mediocre Bombard at Home City gather point")]
        public string BigGunToolTip {
            get {
                return ((string)(this["BigGunToolTip"]));
            }
            set {
                this["BigGunToolTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tuck tuck tuck")]
        public string MonsterTruck {
            get {
                return ((string)(this["MonsterTruck"]));
            }
            set {
                this["MonsterTruck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Spawn The Tommynator (big red monster truck) at Home City gather point")]
        public string MonsterTruckToolTip {
            get {
                return ((string)(this["MonsterTruckToolTip"]));
            }
            set {
                this["MonsterTruckToolTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ya gotta make do with what ya got")]
        public string CustomItem1 {
            get {
                return ((string)(this["CustomItem1"]));
            }
            set {
                this["CustomItem1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Age of Empires III")]
        public string WindowTitle {
            get {
                return ((string)(this["WindowTitle"]));
            }
            set {
                this["WindowTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("speed always wins")]
        public string BuildRateTag {
            get {
                return ((string)(this["BuildRateTag"]));
            }
            set {
                this["BuildRateTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomItem1ToolTip {
            get {
                return ((string)(this["CustomItem1ToolTip"]));
            }
            set {
                this["CustomItem1ToolTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A recent study indicated that 100% of herdables are obese")]
        public string FlattenAnimals {
            get {
                return ((string)(this["FlattenAnimals"]));
            }
            set {
                this["FlattenAnimals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tuck tuck tuck")]
        public string CustomItem2 {
            get {
                return ((string)(this["CustomItem2"]));
            }
            set {
                this["CustomItem2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomItem2Tooltip {
            get {
                return ((string)(this["CustomItem2Tooltip"]));
            }
            set {
                this["CustomItem2Tooltip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Where\'s that axe?")]
        public string CustomItem3 {
            get {
                return ((string)(this["CustomItem3"]));
            }
            set {
                this["CustomItem3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomItem3ToolTip {
            get {
                return ((string)(this["CustomItem3ToolTip"]));
            }
            set {
                this["CustomItem3ToolTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomItem4 {
            get {
                return ((string)(this["CustomItem4"]));
            }
            set {
                this["CustomItem4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomItem4Tooltip {
            get {
                return ((string)(this["CustomItem4Tooltip"]));
            }
            set {
                this["CustomItem4Tooltip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a whole lot of love")]
        public string Exports {
            get {
                return ((string)(this["Exports"]));
            }
            set {
                this["Exports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal SuppliesAmt {
            get {
                return ((decimal)(this["SuppliesAmt"]));
            }
            set {
                this["SuppliesAmt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public decimal XPAmt {
            get {
                return ((decimal)(this["XPAmt"]));
            }
            set {
                this["XPAmt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Custom1Amt {
            get {
                return ((decimal)(this["Custom1Amt"]));
            }
            set {
                this["Custom1Amt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Custom2Amt {
            get {
                return ((decimal)(this["Custom2Amt"]));
            }
            set {
                this["Custom2Amt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Custom3Amt {
            get {
                return ((decimal)(this["Custom3Amt"]));
            }
            set {
                this["Custom3Amt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Custom4Amt {
            get {
                return ((decimal)(this["Custom4Amt"]));
            }
            set {
                this["Custom4Amt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Destroy all Enemy Boats,Musketeered,Instant Victory,Custom2,Custom3,Custom4")]
        public string UnImportantSections {
            get {
                return ((string)(this["UnImportantSections"]));
            }
            set {
                this["UnImportantSections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowTitleComboIndex {
            get {
                return ((int)(this["WindowTitleComboIndex"]));
            }
            set {
                this["WindowTitleComboIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int DelayedSendTime {
            get {
                return ((int)(this["DelayedSendTime"]));
            }
            set {
                this["DelayedSendTime"] = value;
            }
        }
    }
}
